spring:
  datasource:
    url: jdbc:mariadb://meedding.ctoilrrq7tkn.ap-northeast-2.rds.amazonaws.com/tmp
    username: junbeom_kang
    password: wnsqja12
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  redis:
    host: localhost
    port: 6379
    key: ranking
logging.level:
  web: debug
  org.hibernate.SQL: #debug