spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  redis:
    host: localhost
    port: 6379
    key: ranking
  profiles:
    include: security
logging.level:
  web: debug
  org.hibernate.SQL: #debug




